name: Latest anime updates from MyAnimeList
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest anime posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ANIME-LIST"
          feed_list: "https://myanimelist.net/rss.php?type=rw&u=DaSushiAsian"
          template: "$newline* [$title]($url) - $description"
