name: Latest music updates from LastFM
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest anime posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "LASTFM"
          feed_list: "https://splo.me/lastfmrss-working.php?user=lil_sush"
          custom_tags: "link/link"
          template: "$newline* [$title]($link)"
